{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ocelot.config-map-ocelot.fullname" . }}
  annotations:
    avp.kubernetes.io/path: {{ .Values.avp }}
data:
  configuration.json: |-
    {
      "Routes": [
       {
      "DownstreamPathTemplate": "/{everything}",
      "DownstreamScheme": "{{ .Values.config.downstreamScheme }}",
      "DownstreamHostAndPorts": [
        {
          "Host": "{{ .Values.config.downstreamHostAndPorts.host }}",
          "Port": {{ .Values.config.downstreamHostAndPorts.port }},
        }
          ],
          "UpstreamPathTemplate": "/{{.Values.dnsSubPath}}/{everything}",
          "UpstreamHttpMethod": [
            "Get","Post", "Delete", "Put"
          ]
        }
          ],
          "GlobalConfiguration": {
            "BaseUrl": "/"
          }
    }

{{- end }}
