{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ocelot.config-map.fullname" . }}
  annotations:
    avp.kubernetes.io/path: {{ .Values.avp }}
data:
  appsettings.json: |-
    {
      "App": {
            "CorsOrigins": "{{ .Values.config.corsOrigins }}"
        },
        "Logging": {
        "LogLevel": {
            "Default": "Information",
            "Microsoft": "Warning",
            "Microsoft.Hosting.Lifetime": "Information"
            }
        },
        "AllowedHosts": "*"
    }
    
{{- end }}
