apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: http
  selector:
    app: {{ .Chart.Name }}

