{{- if .Values.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  annotations:
    avp.kubernetes.io/path: {{ .Values.avp }}
spec:
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: http
  selector:
    app: {{ .Chart.Name }}
{{- end }}

