{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "public-web.config-map.fullname" . }}
  annotations:
    avp.kubernetes.io/path: {{ .Values.avp }}
data:
  configuration.js: |-
      var baseUrl = "{{ .Values.config.baseUrl }}";

      dynamic_configuration = {
          production: false,
          application: {
              baseUrl,
              name: 'FasehAI',
          },
          oAuthConfig: {
              issuer: "{{ .Values.config.issuer }}",
              redirectUri: baseUrl,
              clientId: 'FasehAI_App',
              responseType: 'code',
              scope: 'offline_access FasehAI',
          },
          apis: {
              default: {
                  url: "{{ .Values.config.apis.default.url }}",
                  rootNamespace: 'Thiqah.FasehAI',
              },
          },
      }

{{- end }}
